ISSUE ======== fatal error when clicking the FAB in TermActivity
# HOW SHOULD IT WORK
Activity should load on click
- creating TermAddActivity and related layouts

# CAUSES
Class issues? Class was created manually

# SOLUTION
- researched issue on google, found that **public** could be missing
- added **public** to the TermsAddActivity Class
- tested, SUCCESS

# REFERENCE
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wguscheduler, PID: 5152
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.wguscheduler/com.example.wguscheduler.activities.TermAddActivity}: java.lang.IllegalAccessException: java.lang.Class<com.example.wguscheduler.activities.TermAddActivity> is not accessible from java.lang.Class<android.app.AppComponentFactory>